name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Git check
        run: |
          git status && cd lua && git status

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/bake-action@master
        with:
          targets: github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/trunk' }}
        with:
          cname: htm-badge.apparea.dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
